# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile

jaffle_shop:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: 10.100.60.152
      port: 5432
      user: postgres
      pass: root
      dbname: staging_ao
      schema: raw_jaffle_shop
    prod:
      type: redshift
      threads: 1
      host: 127.0.0.1
      port: 5439
      user: alice
      pass: pa55word
      dbname: warehouse
      schema: analytics
  target: dev

